networks:
  ollama:

volumes:
  chromadb_data:

services:
  ollama:
    image: ollama/ollama
    networks:
      - ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    volumes:
      - ./data/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3002:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama

  packet_buddy:
    image: bijouxa/packetbuddy:latest
    restart: always
    environment:
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "8505:8505"     
    volumes:
      - ./config:/root/.streamlit
      - chromadb_data:/app/chromadb 
    depends_on:
      - ollama
    networks:
      - ollama
