---
version: '3'
 
services:
  packet_buddy:
    image: johncapobianco/packet_buddy:packet_buddy    
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8505:8505"
    volumes:
      - ./config.toml:/root/.streamlit/config.toml      